/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsumerProtectionClubRouteImport } from './routes/consumer-protection-club'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FineArtsClubRouteImport } from './routes/fine-arts-club'
import { Route as InnovationEntrepreneurshipRouteImport } from './routes/innovation-entrepreneurship'
import { Route as InternalGrievancesCommitteeRouteImport } from './routes/internal-grievances-committee'
import { Route as IqacRouteImport } from './routes/iqac'
import { Route as JuniorJciWingRouteImport } from './routes/junior-jci-wing'
import { Route as NssRouteImport } from './routes/nss'
import { Route as PlacementTrainingCellRouteImport } from './routes/placement-training-cell'
import { Route as ResearchDevelopmentCellRouteImport } from './routes/research-development-cell'
import { Route as RotaractClubRouteImport } from './routes/rotaract-club'
import { Route as SwayamNptelRouteImport } from './routes/swayam-nptel'
import { Route as VoterLiteracyClubRouteImport } from './routes/voter-literacy-club'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerProtectionClubRoute = ConsumerProtectionClubRouteImport.update({
  id: '/consumer-protection-club',
  path: '/consumer-protection-club',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FineArtsClubRoute = FineArtsClubRouteImport.update({
  id: '/fine-arts-club',
  path: '/fine-arts-club',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationEntrepreneurshipRoute =
  InnovationEntrepreneurshipRouteImport.update({
    id: '/innovation-entrepreneurship',
    path: '/innovation-entrepreneurship',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalGrievancesCommitteeRoute =
  InternalGrievancesCommitteeRouteImport.update({
    id: '/internal-grievances-committee',
    path: '/internal-grievances-committee',
    getParentRoute: () => rootRouteImport,
  } as any)
const IqacRoute = IqacRouteImport.update({
  id: '/iqac',
  path: '/iqac',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorJciWingRoute = JuniorJciWingRouteImport.update({
  id: '/junior-jci-wing',
  path: '/junior-jci-wing',
  getParentRoute: () => rootRouteImport,
} as any)
const NssRoute = NssRouteImport.update({
  id: '/nss',
  path: '/nss',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementTrainingCellRoute = PlacementTrainingCellRouteImport.update({
  id: '/placement-training-cell',
  path: '/placement-training-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchDevelopmentCellRoute = ResearchDevelopmentCellRouteImport.update({
  id: '/research-development-cell',
  path: '/research-development-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaractClubRoute = RotaractClubRouteImport.update({
  id: '/rotaract-club',
  path: '/rotaract-club',
  getParentRoute: () => rootRouteImport,
} as any)
const SwayamNptelRoute = SwayamNptelRouteImport.update({
  id: '/swayam-nptel',
  path: '/swayam-nptel',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterLiteracyClubRoute = VoterLiteracyClubRouteImport.update({
  id: '/voter-literacy-club',
  path: '/voter-literacy-club',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consumer-protection-club': typeof ConsumerProtectionClubRoute
  '/contact': typeof ContactRoute
  '/fine-arts-club': typeof FineArtsClubRoute
  '/innovation-entrepreneurship': typeof InnovationEntrepreneurshipRoute
  '/internal-grievances-committee': typeof InternalGrievancesCommitteeRoute
  '/iqac': typeof IqacRoute
  '/junior-jci-wing': typeof JuniorJciWingRoute
  '/nss': typeof NssRoute
  '/placement-training-cell': typeof PlacementTrainingCellRoute
  '/research-development-cell': typeof ResearchDevelopmentCellRoute
  '/rotaract-club': typeof RotaractClubRoute
  '/swayam-nptel': typeof SwayamNptelRoute
  '/voter-literacy-club': typeof VoterLiteracyClubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consumer-protection-club': typeof ConsumerProtectionClubRoute
  '/contact': typeof ContactRoute
  '/fine-arts-club': typeof FineArtsClubRoute
  '/innovation-entrepreneurship': typeof InnovationEntrepreneurshipRoute
  '/internal-grievances-committee': typeof InternalGrievancesCommitteeRoute
  '/iqac': typeof IqacRoute
  '/junior-jci-wing': typeof JuniorJciWingRoute
  '/nss': typeof NssRoute
  '/placement-training-cell': typeof PlacementTrainingCellRoute
  '/research-development-cell': typeof ResearchDevelopmentCellRoute
  '/rotaract-club': typeof RotaractClubRoute
  '/swayam-nptel': typeof SwayamNptelRoute
  '/voter-literacy-club': typeof VoterLiteracyClubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consumer-protection-club': typeof ConsumerProtectionClubRoute
  '/contact': typeof ContactRoute
  '/fine-arts-club': typeof FineArtsClubRoute
  '/innovation-entrepreneurship': typeof InnovationEntrepreneurshipRoute
  '/internal-grievances-committee': typeof InternalGrievancesCommitteeRoute
  '/iqac': typeof IqacRoute
  '/junior-jci-wing': typeof JuniorJciWingRoute
  '/nss': typeof NssRoute
  '/placement-training-cell': typeof PlacementTrainingCellRoute
  '/research-development-cell': typeof ResearchDevelopmentCellRoute
  '/rotaract-club': typeof RotaractClubRoute
  '/swayam-nptel': typeof SwayamNptelRoute
  '/voter-literacy-club': typeof VoterLiteracyClubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consumer-protection-club'
    | '/contact'
    | '/fine-arts-club'
    | '/innovation-entrepreneurship'
    | '/internal-grievances-committee'
    | '/iqac'
    | '/junior-jci-wing'
    | '/nss'
    | '/placement-training-cell'
    | '/research-development-cell'
    | '/rotaract-club'
    | '/swayam-nptel'
    | '/voter-literacy-club'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consumer-protection-club'
    | '/contact'
    | '/fine-arts-club'
    | '/innovation-entrepreneurship'
    | '/internal-grievances-committee'
    | '/iqac'
    | '/junior-jci-wing'
    | '/nss'
    | '/placement-training-cell'
    | '/research-development-cell'
    | '/rotaract-club'
    | '/swayam-nptel'
    | '/voter-literacy-club'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consumer-protection-club'
    | '/contact'
    | '/fine-arts-club'
    | '/innovation-entrepreneurship'
    | '/internal-grievances-committee'
    | '/iqac'
    | '/junior-jci-wing'
    | '/nss'
    | '/placement-training-cell'
    | '/research-development-cell'
    | '/rotaract-club'
    | '/swayam-nptel'
    | '/voter-literacy-club'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsumerProtectionClubRoute: typeof ConsumerProtectionClubRoute
  ContactRoute: typeof ContactRoute
  FineArtsClubRoute: typeof FineArtsClubRoute
  InnovationEntrepreneurshipRoute: typeof InnovationEntrepreneurshipRoute
  InternalGrievancesCommitteeRoute: typeof InternalGrievancesCommitteeRoute
  IqacRoute: typeof IqacRoute
  JuniorJciWingRoute: typeof JuniorJciWingRoute
  NssRoute: typeof NssRoute
  PlacementTrainingCellRoute: typeof PlacementTrainingCellRoute
  ResearchDevelopmentCellRoute: typeof ResearchDevelopmentCellRoute
  RotaractClubRoute: typeof RotaractClubRoute
  SwayamNptelRoute: typeof SwayamNptelRoute
  VoterLiteracyClubRoute: typeof VoterLiteracyClubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer-protection-club': {
      id: '/consumer-protection-club'
      path: '/consumer-protection-club'
      fullPath: '/consumer-protection-club'
      preLoaderRoute: typeof ConsumerProtectionClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fine-arts-club': {
      id: '/fine-arts-club'
      path: '/fine-arts-club'
      fullPath: '/fine-arts-club'
      preLoaderRoute: typeof FineArtsClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-entrepreneurship': {
      id: '/innovation-entrepreneurship'
      path: '/innovation-entrepreneurship'
      fullPath: '/innovation-entrepreneurship'
      preLoaderRoute: typeof InnovationEntrepreneurshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-grievances-committee': {
      id: '/internal-grievances-committee'
      path: '/internal-grievances-committee'
      fullPath: '/internal-grievances-committee'
      preLoaderRoute: typeof InternalGrievancesCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqac': {
      id: '/iqac'
      path: '/iqac'
      fullPath: '/iqac'
      preLoaderRoute: typeof IqacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junior-jci-wing': {
      id: '/junior-jci-wing'
      path: '/junior-jci-wing'
      fullPath: '/junior-jci-wing'
      preLoaderRoute: typeof JuniorJciWingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nss': {
      id: '/nss'
      path: '/nss'
      fullPath: '/nss'
      preLoaderRoute: typeof NssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-training-cell': {
      id: '/placement-training-cell'
      path: '/placement-training-cell'
      fullPath: '/placement-training-cell'
      preLoaderRoute: typeof PlacementTrainingCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-development-cell': {
      id: '/research-development-cell'
      path: '/research-development-cell'
      fullPath: '/research-development-cell'
      preLoaderRoute: typeof ResearchDevelopmentCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotaract-club': {
      id: '/rotaract-club'
      path: '/rotaract-club'
      fullPath: '/rotaract-club'
      preLoaderRoute: typeof RotaractClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swayam-nptel': {
      id: '/swayam-nptel'
      path: '/swayam-nptel'
      fullPath: '/swayam-nptel'
      preLoaderRoute: typeof SwayamNptelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter-literacy-club': {
      id: '/voter-literacy-club'
      path: '/voter-literacy-club'
      fullPath: '/voter-literacy-club'
      preLoaderRoute: typeof VoterLiteracyClubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsumerProtectionClubRoute: ConsumerProtectionClubRoute,
  ContactRoute: ContactRoute,
  FineArtsClubRoute: FineArtsClubRoute,
  InnovationEntrepreneurshipRoute: InnovationEntrepreneurshipRoute,
  InternalGrievancesCommitteeRoute: InternalGrievancesCommitteeRoute,
  IqacRoute: IqacRoute,
  JuniorJciWingRoute: JuniorJciWingRoute,
  NssRoute: NssRoute,
  PlacementTrainingCellRoute: PlacementTrainingCellRoute,
  ResearchDevelopmentCellRoute: ResearchDevelopmentCellRoute,
  RotaractClubRoute: RotaractClubRoute,
  SwayamNptelRoute: SwayamNptelRoute,
  VoterLiteracyClubRoute: VoterLiteracyClubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
